### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Wonskii** [1f1n/solana-token-top-traders#1]
getting a 403 error when running the script, but can access the website manually. Any idea on fixing?

Error fetching data for GS9Xa2Nroc7FfNZSz5UbmyvyekxwBtFQD2273FFgpump: 403 Client Error: Forbidden for url: https://gmgn.ai/defi/quotation/v1/tokens/top_traders/sol/GS9Xa2Nroc7FfNZSz5UbmyvyekxwBtFQD2273FFgpump?orderby=profit&direction=desc

**Comment by 1f1n** [comment]
Fixed
